name: Build

on:
  push:
    branches: [ main ]
    tags:
    - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  test-gradle:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: ['21', '25']
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          # cache-dependency-path: |
          #   ./**/*.gradle.kts
          #   ./gradle/wrapper/gradle-wrapper.properties
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Test
        run: ./gradlew check --no-daemon
      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: always() # This ensures that test results are uploaded even if the test step fails
        with:
          name: test-results-${{ matrix.java-version }}
          path: |
            **/build/reports/
            **/build/test-results/
