package org.funfix.delayedqueue.jvm.internals.jdbc.hsqldb

import org.funfix.delayedqueue.jvm.internals.jdbc.Migration

/** HSQLDB-specific migrations for the DelayedQueue table. */
internal object HSQLDBMigrations {
    /**
     * Gets the list of migrations for HSQLDB.
     *
     * @param tableName The name of the delayed queue table
     * @return List of migrations in order
     */
    fun getMigrations(tableName: String): List<Migration> =
        listOf(
            Migration.createTableIfNotExists(
                tableName = tableName,
                sql =
                    """
                    CREATE TABLE "$tableName" (
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "pKey" VARCHAR(200) NOT NULL,
                        "pKind" VARCHAR(100) NOT NULL,
                        "payload" BLOB(16777216) NOT NULL,
                        "scheduledAt" BIGINT NOT NULL,
                        "scheduledAtInitially" BIGINT NOT NULL,
                        "lockUuid" VARCHAR(36) NULL,
                        "createdAt" BIGINT NOT NULL
                    );

                    CREATE UNIQUE INDEX "${tableName}__PKindPKeyUniqueIndex"
                    ON "$tableName" ("pKind", "pKey");

                    CREATE INDEX "${tableName}__KindPlusScheduledAtIndex"
                    ON "$tableName" ("pKind", "scheduledAt");

                    CREATE INDEX "${tableName}__LockUuidPlusIdIndex"
                    ON "$tableName" ("lockUuid", "id");
                    """,
            )
        )
}
