package org.funfix.delayedqueue.jvm.internals.jdbc.oracle

import org.funfix.delayedqueue.jvm.internals.jdbc.Migration

/** Oracle-specific migrations for the DelayedQueue table. */
internal object OracleMigrations {
    /**
     * Gets the list of migrations for Oracle.
     *
     * @param tableName The name of the delayed queue table
     * @return List of migrations in order
     */
    fun getMigrations(tableName: String): List<Migration> =
        listOf(
            Migration.createTableIfNotExists(
                tableName = tableName,
                sql =
                    """
                    CREATE TABLE "$tableName" (
                        "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "pKey" VARCHAR2(200) NOT NULL,
                        "pKind" VARCHAR2(100) NOT NULL,
                        "payload" BLOB NOT NULL,
                        "scheduledAt" NUMBER(19) NOT NULL,
                        "scheduledAtInitially" NUMBER(19) NOT NULL,
                        "lockUuid" VARCHAR2(36) NULL,
                        "createdAt" NUMBER(19) NOT NULL
                    );

                    CREATE UNIQUE INDEX "${tableName}__PKeyPlusKindUniqueIndex"
                    ON "$tableName"("pKey", "pKind");

                    CREATE INDEX "${tableName}__KindPlusScheduledAtIndex"
                    ON "$tableName"("pKind", "scheduledAt");

                    CREATE INDEX "${tableName}__LockUuidPlusIdIndex"
                    ON "$tableName"("lockUuid", "id");
                    """,
            )
        )
}
